CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),

  PRIMARY KEY(id),
  UNIQUE(email)
)
